<?php

/*
 * Auto-generated by libasynql-def
 * Created from mysql.sql
 */

declare(strict_types=1);

namespace adeynes\cucumber\utils;

interface Queries
{
    
    /**
     * <h4>Declared in:</h4>
     * - /home/alexis/pmmp/plugins/dev-cucumber/resources/mysql.sql:64
     *
     * <h3>Variables</h3>
     * - <code>:name</code> string, required in mysql.sql
     * - <code>:ip</code> string, required in mysql.sql
     */
    public const CUCUMBER_ADD_PLAYER = "cucumber.add.player";

    /**
     * <h4>Declared in:</h4>
     * - /home/alexis/pmmp/plugins/dev-cucumber/resources/mysql.sql:71
     *
     * <h3>Variables</h3>
     * - <code>:name</code> string, required in mysql.sql
     */
    public const CUCUMBER_GET_PLAYER_BY_NAME = "cucumber.get.player.by-name";

    /**
     * <h4>Declared in:</h4>
     * - /home/alexis/pmmp/plugins/dev-cucumber/resources/mysql.sql:78
     */
    public const CUCUMBER_GET_PUNISHMENTS_BANS = "cucumber.get.punishments.bans";

    /**
     * <h4>Declared in:</h4>
     * - /home/alexis/pmmp/plugins/dev-cucumber/resources/mysql.sql:81
     */
    public const CUCUMBER_GET_PUNISHMENTS_IP_BANS = "cucumber.get.punishments.ip-bans";

    /**
     * <h4>Declared in:</h4>
     * - /home/alexis/pmmp/plugins/dev-cucumber/resources/mysql.sql:89
     */
    public const CUCUMBER_GET_PUNISHMENTS_MUTES = "cucumber.get.punishments.mutes";

    /**
     * <h4>Declared in:</h4>
     * - /home/alexis/pmmp/plugins/dev-cucumber/resources/mysql.sql:84
     */
    public const CUCUMBER_GET_PUNISHMENTS_UBANS = "cucumber.get.punishments.ubans";

    /**
     * <h4>Declared in:</h4>
     * - /home/alexis/pmmp/plugins/dev-cucumber/resources/mysql.sql:12
     */
    public const CUCUMBER_INIT_PLAYERS = "cucumber.init.players";

    /**
     * <h4>Declared in:</h4>
     * - /home/alexis/pmmp/plugins/dev-cucumber/resources/mysql.sql:24
     */
    public const CUCUMBER_INIT_PUNISHMENTS_BANS = "cucumber.init.punishments.bans";

    /**
     * <h4>Declared in:</h4>
     * - /home/alexis/pmmp/plugins/dev-cucumber/resources/mysql.sql:34
     */
    public const CUCUMBER_INIT_PUNISHMENTS_IP_BANS = "cucumber.init.punishments.ip-bans";

    /**
     * <h4>Declared in:</h4>
     * - /home/alexis/pmmp/plugins/dev-cucumber/resources/mysql.sql:54
     */
    public const CUCUMBER_INIT_PUNISHMENTS_MUTES = "cucumber.init.punishments.mutes";

    /**
     * <h4>Declared in:</h4>
     * - /home/alexis/pmmp/plugins/dev-cucumber/resources/mysql.sql:43
     */
    public const CUCUMBER_INIT_PUNISHMENTS_UBANS = "cucumber.init.punishments.ubans";

    /**
     * <h4>Declared in:</h4>
     * - /home/alexis/pmmp/plugins/dev-cucumber/resources/mysql.sql:100
     *
     * <h3>Variables</h3>
     * - <code>:expiration</code> int, required in mysql.sql
     * - <code>:moderator</code> string, required in mysql.sql
     * - <code>:reason</code> string, required in mysql.sql
     * - <code>:name</code> string, required in mysql.sql
     */
    public const CUCUMBER_PUNISH_BAN = "cucumber.punish.ban";

    /**
     * <h4>Declared in:</h4>
     * - /home/alexis/pmmp/plugins/dev-cucumber/resources/mysql.sql:117
     *
     * <h3>Variables</h3>
     * - <code>:expiration</code> int, required in mysql.sql
     * - <code>:moderator</code> string, required in mysql.sql
     * - <code>:reason</code> string, required in mysql.sql
     * - <code>:ip</code> string, required in mysql.sql
     */
    public const CUCUMBER_PUNISH_IP_BAN = "cucumber.punish.ip-ban";

    /**
     * <h4>Declared in:</h4>
     * - /home/alexis/pmmp/plugins/dev-cucumber/resources/mysql.sql:121
     *
     * <h3>Variables</h3>
     * - <code>:ip</code> string, required in mysql.sql
     */
    public const CUCUMBER_PUNISH_IP_UNBAN = "cucumber.punish.ip-unban";

    /**
     * <h4>Declared in:</h4>
     * - /home/alexis/pmmp/plugins/dev-cucumber/resources/mysql.sql:136
     *
     * <h3>Variables</h3>
     * - <code>:expiration</code> int, required in mysql.sql
     * - <code>:moderator</code> string, required in mysql.sql
     * - <code>:reason</code> string, required in mysql.sql
     * - <code>:name</code> string, required in mysql.sql
     */
    public const CUCUMBER_PUNISH_MUTE = "cucumber.punish.mute";

    /**
     * <h4>Declared in:</h4>
     * - /home/alexis/pmmp/plugins/dev-cucumber/resources/mysql.sql:128
     *
     * <h3>Variables</h3>
     * - <code>:moderator</code> string, required in mysql.sql
     * - <code>:reason</code> string, required in mysql.sql
     * - <code>:ip</code> string, required in mysql.sql
     */
    public const CUCUMBER_PUNISH_UBAN = "cucumber.punish.uban";

    /**
     * <h4>Declared in:</h4>
     * - /home/alexis/pmmp/plugins/dev-cucumber/resources/mysql.sql:109
     *
     * <h3>Variables</h3>
     * - <code>:name</code> string, required in mysql.sql
     */
    public const CUCUMBER_PUNISH_UNBAN = "cucumber.punish.unban";

    /**
     * <h4>Declared in:</h4>
     * - /home/alexis/pmmp/plugins/dev-cucumber/resources/mysql.sql:145
     *
     * <h3>Variables</h3>
     * - <code>:name</code> string, required in mysql.sql
     */
    public const CUCUMBER_PUNISH_UNMUTE = "cucumber.punish.unmute";

}
